name: interactiveplus_shared_dart
description: A starting point for Dart libraries or applications.
version: 0.0.11
homepage: https://www.interactiveplus.org
repository: https://github.com/InteractivePlus/interactiveplus_shared_dart

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.20.1
dependencies: 
  equatable: ^2.0.3
  hex: ^0.2.0
  intl: ^0.17.0
