name: interactiveplus_exchangeformat_client
description: Package that 
version: 0.0.1
# homepage: https://www.example.com
repository: https://github.com/InteractivePlus/interactiveplus_shared_dart

environment:
  sdk: '>=2.15.1 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies: 
  http: ^0.13.4
  interactiveplus_exchangeformat: ^0.0.6
  interactiveplus_shared_dart: ^0.0.12
